### ISSUE TITLE
Week 3 Task List

### ISSUE THREAD

**Issue by alyona-chur** [ASKYI/-staff-time#1]
- [x] Реализовать базу данных в MSSQL

- [x] Заполнить повторяющимися конструкциями основную таблицу (>=1000 строк)

- [x] Создать класс, описывающий задачу (несколько свойств взять из ТЗ)

- [x] Считать структурированно дерево

**Comment by alyona-chur** [comment]
- Разные версии БД (пустая, с красивым-коротким тестом, заполненная гигантским муссором) в папке BDscripts.

- Есть подходящая версия БД

- Было создано приложение TestTree, которое взаимодействует с БД через EF, читает информацию о задачах, выводит в виде дерева с помощью TreeView.
