### ISSUE TITLE
Week 4 Task List

### ISSUE THREAD

**Issue by alyona-chur** [ASKYI/-staff-time#2]
- [x] Создать основное окно (для тестов, не конечный вариант)

- [x] Создать элемент, позволяющий древовидно отображать задачи (внутри задачи будем потом добавлять кнопки и разную аналитику)

- [x] Создать элемент, избранное

**Comment by alyona-chur** [comment]
- Вместо основного окна - окно с деревом и избранным.

- Информация о задачах, выводится в виде дерева с помощью TreeView.

- Для элемента избранное не готов элемент, способный отобразить его.

**Comment by alyona-chur** [comment]
- Избранное в DataGrid. После будет модифицированно до цепочки пути.
